parser: babel-eslint
extends:
  - airbnb-base
  - plugin:flowtype/recommended
plugins:
  - flowtype
  - eslint-plugin-import-order-alphabetical
  - jsdoc
env:
  node: true
  mocha: true
rules:
  no-param-reassign: "off"
  import/no-unresolved:
    - error
    - commonjs: true
      ignore: [ ^aws-sdk$, ^oracledb$, ^request-promise-native$, contrib/ ]
  jsdoc/require-param:
    - warn
    - exemptedBy: [ type ]
  jsdoc/require-returns:
    - warn
    - exemptedBy: [ type ]
  jsdoc/no-undefined-types:
    - warn
      # Express and gulpfile types
    - definedTypes:
        - RequestHandler
        - ErrorRequestHandler
        - Request
        - Response
        - Stream
        - ChildProcess
  jsdoc/require-jsdoc:
    - warn
    - publicOnly: true
      require:
        ArrowFunctionExpression: true
settings:
  import/resolver:
    babel-module: {}
