server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

dataSources:
  dataSources: ['ldap']
  ldap:
    url: 'ldaps://ldap.onid.orst.edu'
